/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TtIndexRouteImport } from './routes/tt/index'
import { Route as TimetableIndexRouteImport } from './routes/timetable/index'
import { Route as DemoTrpcTodoRouteImport } from './routes/demo/trpc-todo'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as TtTimetableIdRouteRouteImport } from './routes/tt/$timetableId/route'
import { Route as TimetableTimetableIdRouteRouteImport } from './routes/timetable/$timetableId/route'
import { Route as TimetableTimetableIdIndexRouteImport } from './routes/timetable/$timetableId/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as TtTimetableIdLayoutRouteRouteImport } from './routes/tt/$timetableId/_layout/route'
import { Route as TtTimetableIdLayoutTimetablesRouteImport } from './routes/tt/$timetableId/_layout/timetables'
import { Route as TtTimetableIdLayoutTeachersRouteImport } from './routes/tt/$timetableId/_layout/teachers'
import { Route as TtTimetableIdLayoutSubjectsRouteImport } from './routes/tt/$timetableId/_layout/subjects'
import { Route as TtTimetableIdLayoutSubdivisionsRouteImport } from './routes/tt/$timetableId/_layout/subdivisions'
import { Route as TtTimetableIdLayoutLecturesRouteImport } from './routes/tt/$timetableId/_layout/lectures'
import { Route as TtTimetableIdLayoutGroupsRouteImport } from './routes/tt/$timetableId/_layout/groups'
import { Route as TtTimetableIdLayoutClassroomsRouteImport } from './routes/tt/$timetableId/_layout/classrooms'
import { Route as TtTimetableIdLayoutEditIndexRouteImport } from './routes/tt/$timetableId/_layout/edit/index'
import { ServerRoute as McpServerRouteImport } from './routes/mcp'
import { ServerRoute as ApiMcpTodosServerRouteImport } from './routes/api/mcp-todos'
import { ServerRoute as ApiDemoTqTodosServerRouteImport } from './routes/api/demo-tq-todos'
import { ServerRoute as ApiDemoNamesServerRouteImport } from './routes/api/demo-names'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api/trpc.$'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TtIndexRoute = TtIndexRouteImport.update({
  id: '/tt/',
  path: '/tt/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableIndexRoute = TimetableIndexRouteImport.update({
  id: '/timetable/',
  path: '/timetable/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTrpcTodoRoute = DemoTrpcTodoRouteImport.update({
  id: '/demo/trpc-todo',
  path: '/demo/trpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TtTimetableIdRouteRoute = TtTimetableIdRouteRouteImport.update({
  id: '/tt/$timetableId',
  path: '/tt/$timetableId',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableTimetableIdRouteRoute =
  TimetableTimetableIdRouteRouteImport.update({
    id: '/timetable/$timetableId',
    path: '/timetable/$timetableId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TimetableTimetableIdIndexRoute =
  TimetableTimetableIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TimetableTimetableIdRouteRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const TtTimetableIdLayoutRouteRoute =
  TtTimetableIdLayoutRouteRouteImport.update({
    id: '/_layout',
    getParentRoute: () => TtTimetableIdRouteRoute,
  } as any)
const TtTimetableIdLayoutTimetablesRoute =
  TtTimetableIdLayoutTimetablesRouteImport.update({
    id: '/timetables',
    path: '/timetables',
    getParentRoute: () => TtTimetableIdLayoutRouteRoute,
  } as any)
const TtTimetableIdLayoutTeachersRoute =
  TtTimetableIdLayoutTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => TtTimetableIdLayoutRouteRoute,
  } as any)
const TtTimetableIdLayoutSubjectsRoute =
  TtTimetableIdLayoutSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => TtTimetableIdLayoutRouteRoute,
  } as any)
const TtTimetableIdLayoutSubdivisionsRoute =
  TtTimetableIdLayoutSubdivisionsRouteImport.update({
    id: '/subdivisions',
    path: '/subdivisions',
    getParentRoute: () => TtTimetableIdLayoutRouteRoute,
  } as any)
const TtTimetableIdLayoutLecturesRoute =
  TtTimetableIdLayoutLecturesRouteImport.update({
    id: '/lectures',
    path: '/lectures',
    getParentRoute: () => TtTimetableIdLayoutRouteRoute,
  } as any)
const TtTimetableIdLayoutGroupsRoute =
  TtTimetableIdLayoutGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => TtTimetableIdLayoutRouteRoute,
  } as any)
const TtTimetableIdLayoutClassroomsRoute =
  TtTimetableIdLayoutClassroomsRouteImport.update({
    id: '/classrooms',
    path: '/classrooms',
    getParentRoute: () => TtTimetableIdLayoutRouteRoute,
  } as any)
const TtTimetableIdLayoutEditIndexRoute =
  TtTimetableIdLayoutEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => TtTimetableIdLayoutRouteRoute,
  } as any)
const McpServerRoute = McpServerRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMcpTodosServerRoute = ApiMcpTodosServerRouteImport.update({
  id: '/api/mcp-todos',
  path: '/api/mcp-todos',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiDemoTqTodosServerRoute = ApiDemoTqTodosServerRouteImport.update({
  id: '/api/demo-tq-todos',
  path: '/api/demo-tq-todos',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiDemoNamesServerRoute = ApiDemoNamesServerRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/timetable/$timetableId': typeof TimetableTimetableIdRouteRouteWithChildren
  '/tt/$timetableId': typeof TtTimetableIdLayoutRouteRouteWithChildren
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/timetable': typeof TimetableIndexRoute
  '/tt': typeof TtIndexRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/timetable/$timetableId/': typeof TimetableTimetableIdIndexRoute
  '/tt/$timetableId/classrooms': typeof TtTimetableIdLayoutClassroomsRoute
  '/tt/$timetableId/groups': typeof TtTimetableIdLayoutGroupsRoute
  '/tt/$timetableId/lectures': typeof TtTimetableIdLayoutLecturesRoute
  '/tt/$timetableId/subdivisions': typeof TtTimetableIdLayoutSubdivisionsRoute
  '/tt/$timetableId/subjects': typeof TtTimetableIdLayoutSubjectsRoute
  '/tt/$timetableId/teachers': typeof TtTimetableIdLayoutTeachersRoute
  '/tt/$timetableId/timetables': typeof TtTimetableIdLayoutTimetablesRoute
  '/tt/$timetableId/edit': typeof TtTimetableIdLayoutEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tt/$timetableId': typeof TtTimetableIdLayoutRouteRouteWithChildren
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/timetable': typeof TimetableIndexRoute
  '/tt': typeof TtIndexRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/timetable/$timetableId': typeof TimetableTimetableIdIndexRoute
  '/tt/$timetableId/classrooms': typeof TtTimetableIdLayoutClassroomsRoute
  '/tt/$timetableId/groups': typeof TtTimetableIdLayoutGroupsRoute
  '/tt/$timetableId/lectures': typeof TtTimetableIdLayoutLecturesRoute
  '/tt/$timetableId/subdivisions': typeof TtTimetableIdLayoutSubdivisionsRoute
  '/tt/$timetableId/subjects': typeof TtTimetableIdLayoutSubjectsRoute
  '/tt/$timetableId/teachers': typeof TtTimetableIdLayoutTeachersRoute
  '/tt/$timetableId/timetables': typeof TtTimetableIdLayoutTimetablesRoute
  '/tt/$timetableId/edit': typeof TtTimetableIdLayoutEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/timetable/$timetableId': typeof TimetableTimetableIdRouteRouteWithChildren
  '/tt/$timetableId': typeof TtTimetableIdRouteRouteWithChildren
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/timetable/': typeof TimetableIndexRoute
  '/tt/': typeof TtIndexRoute
  '/tt/$timetableId/_layout': typeof TtTimetableIdLayoutRouteRouteWithChildren
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/timetable/$timetableId/': typeof TimetableTimetableIdIndexRoute
  '/tt/$timetableId/_layout/classrooms': typeof TtTimetableIdLayoutClassroomsRoute
  '/tt/$timetableId/_layout/groups': typeof TtTimetableIdLayoutGroupsRoute
  '/tt/$timetableId/_layout/lectures': typeof TtTimetableIdLayoutLecturesRoute
  '/tt/$timetableId/_layout/subdivisions': typeof TtTimetableIdLayoutSubdivisionsRoute
  '/tt/$timetableId/_layout/subjects': typeof TtTimetableIdLayoutSubjectsRoute
  '/tt/$timetableId/_layout/teachers': typeof TtTimetableIdLayoutTeachersRoute
  '/tt/$timetableId/_layout/timetables': typeof TtTimetableIdLayoutTimetablesRoute
  '/tt/$timetableId/_layout/edit/': typeof TtTimetableIdLayoutEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/timetable/$timetableId'
    | '/tt/$timetableId'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/timetable'
    | '/tt'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/timetable/$timetableId/'
    | '/tt/$timetableId/classrooms'
    | '/tt/$timetableId/groups'
    | '/tt/$timetableId/lectures'
    | '/tt/$timetableId/subdivisions'
    | '/tt/$timetableId/subjects'
    | '/tt/$timetableId/teachers'
    | '/tt/$timetableId/timetables'
    | '/tt/$timetableId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tt/$timetableId'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/timetable'
    | '/tt'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/timetable/$timetableId'
    | '/tt/$timetableId/classrooms'
    | '/tt/$timetableId/groups'
    | '/tt/$timetableId/lectures'
    | '/tt/$timetableId/subdivisions'
    | '/tt/$timetableId/subjects'
    | '/tt/$timetableId/teachers'
    | '/tt/$timetableId/timetables'
    | '/tt/$timetableId/edit'
  id:
    | '__root__'
    | '/'
    | '/timetable/$timetableId'
    | '/tt/$timetableId'
    | '/demo/mcp-todos'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/timetable/'
    | '/tt/'
    | '/tt/$timetableId/_layout'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/timetable/$timetableId/'
    | '/tt/$timetableId/_layout/classrooms'
    | '/tt/$timetableId/_layout/groups'
    | '/tt/$timetableId/_layout/lectures'
    | '/tt/$timetableId/_layout/subdivisions'
    | '/tt/$timetableId/_layout/subjects'
    | '/tt/$timetableId/_layout/teachers'
    | '/tt/$timetableId/_layout/timetables'
    | '/tt/$timetableId/_layout/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimetableTimetableIdRouteRoute: typeof TimetableTimetableIdRouteRouteWithChildren
  TtTimetableIdRouteRoute: typeof TtTimetableIdRouteRouteWithChildren
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTrpcTodoRoute: typeof DemoTrpcTodoRoute
  TimetableIndexRoute: typeof TimetableIndexRoute
  TtIndexRoute: typeof TtIndexRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}
export interface FileServerRoutesByFullPath {
  '/mcp': typeof McpServerRoute
  '/api/demo-names': typeof ApiDemoNamesServerRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosServerRoute
  '/api/mcp-todos': typeof ApiMcpTodosServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/mcp': typeof McpServerRoute
  '/api/demo-names': typeof ApiDemoNamesServerRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosServerRoute
  '/api/mcp-todos': typeof ApiMcpTodosServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/mcp': typeof McpServerRoute
  '/api/demo-names': typeof ApiDemoNamesServerRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosServerRoute
  '/api/mcp-todos': typeof ApiMcpTodosServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/mcp'
    | '/api/demo-names'
    | '/api/demo-tq-todos'
    | '/api/mcp-todos'
    | '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/mcp'
    | '/api/demo-names'
    | '/api/demo-tq-todos'
    | '/api/mcp-todos'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/mcp'
    | '/api/demo-names'
    | '/api/demo-tq-todos'
    | '/api/mcp-todos'
    | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  McpServerRoute: typeof McpServerRoute
  ApiDemoNamesServerRoute: typeof ApiDemoNamesServerRoute
  ApiDemoTqTodosServerRoute: typeof ApiDemoTqTodosServerRoute
  ApiMcpTodosServerRoute: typeof ApiMcpTodosServerRoute
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tt/': {
      id: '/tt/'
      path: '/tt'
      fullPath: '/tt'
      preLoaderRoute: typeof TtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/': {
      id: '/timetable/'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/trpc-todo': {
      id: '/demo/trpc-todo'
      path: '/demo/trpc-todo'
      fullPath: '/demo/trpc-todo'
      preLoaderRoute: typeof DemoTrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tt/$timetableId': {
      id: '/tt/$timetableId'
      path: '/tt/$timetableId'
      fullPath: '/tt/$timetableId'
      preLoaderRoute: typeof TtTimetableIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/$timetableId': {
      id: '/timetable/$timetableId'
      path: '/timetable/$timetableId'
      fullPath: '/timetable/$timetableId'
      preLoaderRoute: typeof TimetableTimetableIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/$timetableId/': {
      id: '/timetable/$timetableId/'
      path: '/'
      fullPath: '/timetable/$timetableId/'
      preLoaderRoute: typeof TimetableTimetableIdIndexRouteImport
      parentRoute: typeof TimetableTimetableIdRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tt/$timetableId/_layout': {
      id: '/tt/$timetableId/_layout'
      path: ''
      fullPath: '/tt/$timetableId'
      preLoaderRoute: typeof TtTimetableIdLayoutRouteRouteImport
      parentRoute: typeof TtTimetableIdRouteRoute
    }
    '/tt/$timetableId/_layout/timetables': {
      id: '/tt/$timetableId/_layout/timetables'
      path: '/timetables'
      fullPath: '/tt/$timetableId/timetables'
      preLoaderRoute: typeof TtTimetableIdLayoutTimetablesRouteImport
      parentRoute: typeof TtTimetableIdLayoutRouteRoute
    }
    '/tt/$timetableId/_layout/teachers': {
      id: '/tt/$timetableId/_layout/teachers'
      path: '/teachers'
      fullPath: '/tt/$timetableId/teachers'
      preLoaderRoute: typeof TtTimetableIdLayoutTeachersRouteImport
      parentRoute: typeof TtTimetableIdLayoutRouteRoute
    }
    '/tt/$timetableId/_layout/subjects': {
      id: '/tt/$timetableId/_layout/subjects'
      path: '/subjects'
      fullPath: '/tt/$timetableId/subjects'
      preLoaderRoute: typeof TtTimetableIdLayoutSubjectsRouteImport
      parentRoute: typeof TtTimetableIdLayoutRouteRoute
    }
    '/tt/$timetableId/_layout/subdivisions': {
      id: '/tt/$timetableId/_layout/subdivisions'
      path: '/subdivisions'
      fullPath: '/tt/$timetableId/subdivisions'
      preLoaderRoute: typeof TtTimetableIdLayoutSubdivisionsRouteImport
      parentRoute: typeof TtTimetableIdLayoutRouteRoute
    }
    '/tt/$timetableId/_layout/lectures': {
      id: '/tt/$timetableId/_layout/lectures'
      path: '/lectures'
      fullPath: '/tt/$timetableId/lectures'
      preLoaderRoute: typeof TtTimetableIdLayoutLecturesRouteImport
      parentRoute: typeof TtTimetableIdLayoutRouteRoute
    }
    '/tt/$timetableId/_layout/groups': {
      id: '/tt/$timetableId/_layout/groups'
      path: '/groups'
      fullPath: '/tt/$timetableId/groups'
      preLoaderRoute: typeof TtTimetableIdLayoutGroupsRouteImport
      parentRoute: typeof TtTimetableIdLayoutRouteRoute
    }
    '/tt/$timetableId/_layout/classrooms': {
      id: '/tt/$timetableId/_layout/classrooms'
      path: '/classrooms'
      fullPath: '/tt/$timetableId/classrooms'
      preLoaderRoute: typeof TtTimetableIdLayoutClassroomsRouteImport
      parentRoute: typeof TtTimetableIdLayoutRouteRoute
    }
    '/tt/$timetableId/_layout/edit/': {
      id: '/tt/$timetableId/_layout/edit/'
      path: '/edit'
      fullPath: '/tt/$timetableId/edit'
      preLoaderRoute: typeof TtTimetableIdLayoutEditIndexRouteImport
      parentRoute: typeof TtTimetableIdLayoutRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/mcp-todos': {
      id: '/api/mcp-todos'
      path: '/api/mcp-todos'
      fullPath: '/api/mcp-todos'
      preLoaderRoute: typeof ApiMcpTodosServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/demo-tq-todos': {
      id: '/api/demo-tq-todos'
      path: '/api/demo-tq-todos'
      fullPath: '/api/demo-tq-todos'
      preLoaderRoute: typeof ApiDemoTqTodosServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface TimetableTimetableIdRouteRouteChildren {
  TimetableTimetableIdIndexRoute: typeof TimetableTimetableIdIndexRoute
}

const TimetableTimetableIdRouteRouteChildren: TimetableTimetableIdRouteRouteChildren =
  {
    TimetableTimetableIdIndexRoute: TimetableTimetableIdIndexRoute,
  }

const TimetableTimetableIdRouteRouteWithChildren =
  TimetableTimetableIdRouteRoute._addFileChildren(
    TimetableTimetableIdRouteRouteChildren,
  )

interface TtTimetableIdLayoutRouteRouteChildren {
  TtTimetableIdLayoutClassroomsRoute: typeof TtTimetableIdLayoutClassroomsRoute
  TtTimetableIdLayoutGroupsRoute: typeof TtTimetableIdLayoutGroupsRoute
  TtTimetableIdLayoutLecturesRoute: typeof TtTimetableIdLayoutLecturesRoute
  TtTimetableIdLayoutSubdivisionsRoute: typeof TtTimetableIdLayoutSubdivisionsRoute
  TtTimetableIdLayoutSubjectsRoute: typeof TtTimetableIdLayoutSubjectsRoute
  TtTimetableIdLayoutTeachersRoute: typeof TtTimetableIdLayoutTeachersRoute
  TtTimetableIdLayoutTimetablesRoute: typeof TtTimetableIdLayoutTimetablesRoute
  TtTimetableIdLayoutEditIndexRoute: typeof TtTimetableIdLayoutEditIndexRoute
}

const TtTimetableIdLayoutRouteRouteChildren: TtTimetableIdLayoutRouteRouteChildren =
  {
    TtTimetableIdLayoutClassroomsRoute: TtTimetableIdLayoutClassroomsRoute,
    TtTimetableIdLayoutGroupsRoute: TtTimetableIdLayoutGroupsRoute,
    TtTimetableIdLayoutLecturesRoute: TtTimetableIdLayoutLecturesRoute,
    TtTimetableIdLayoutSubdivisionsRoute: TtTimetableIdLayoutSubdivisionsRoute,
    TtTimetableIdLayoutSubjectsRoute: TtTimetableIdLayoutSubjectsRoute,
    TtTimetableIdLayoutTeachersRoute: TtTimetableIdLayoutTeachersRoute,
    TtTimetableIdLayoutTimetablesRoute: TtTimetableIdLayoutTimetablesRoute,
    TtTimetableIdLayoutEditIndexRoute: TtTimetableIdLayoutEditIndexRoute,
  }

const TtTimetableIdLayoutRouteRouteWithChildren =
  TtTimetableIdLayoutRouteRoute._addFileChildren(
    TtTimetableIdLayoutRouteRouteChildren,
  )

interface TtTimetableIdRouteRouteChildren {
  TtTimetableIdLayoutRouteRoute: typeof TtTimetableIdLayoutRouteRouteWithChildren
}

const TtTimetableIdRouteRouteChildren: TtTimetableIdRouteRouteChildren = {
  TtTimetableIdLayoutRouteRoute: TtTimetableIdLayoutRouteRouteWithChildren,
}

const TtTimetableIdRouteRouteWithChildren =
  TtTimetableIdRouteRoute._addFileChildren(TtTimetableIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimetableTimetableIdRouteRoute: TimetableTimetableIdRouteRouteWithChildren,
  TtTimetableIdRouteRoute: TtTimetableIdRouteRouteWithChildren,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTrpcTodoRoute: DemoTrpcTodoRoute,
  TimetableIndexRoute: TimetableIndexRoute,
  TtIndexRoute: TtIndexRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  McpServerRoute: McpServerRoute,
  ApiDemoNamesServerRoute: ApiDemoNamesServerRoute,
  ApiDemoTqTodosServerRoute: ApiDemoTqTodosServerRoute,
  ApiMcpTodosServerRoute: ApiMcpTodosServerRoute,
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
